# Generated by Django 3.2.16 on 2022-12-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polzakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpolz', models.CharField(max_length=4000, verbose_name='id пользователя')),
                ('famil', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('otshist', models.CharField(max_length=30, verbose_name='Отчество')),
                ('telefon', models.CharField(max_length=30, verbose_name='Телефон')),
                ('electpoch', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('klass', models.CharField(default='0', max_length=150, verbose_name='Класс')),
                ('chr_class', models.CharField(default='0', max_length=150, verbose_name='Буква класса')),
                ('datareg', models.CharField(max_length=30, verbose_name='Дата регистрации')),
            ],
        ),
    ]
