# Generated by Django 3.2.16 on 2023-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_teachersakt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksAkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.CharField(max_length=30, verbose_name='id учителя')),
                ('studentId', models.CharField(max_length=30, verbose_name='id ученика')),
                ('pole1', models.TextField(default='0', verbose_name='Поле1')),
                ('pole2', models.TextField(default='0', verbose_name='Поле2')),
                ('pole3', models.TextField(default='0', verbose_name='Поле3')),
                ('pole4', models.TextField(default='0', verbose_name='Поле4')),
                ('pole5', models.TextField(default='0', verbose_name='Поле5')),
                ('pole6', models.CharField(max_length=30, verbose_name='Поле6')),
                ('pole7', models.CharField(max_length=1000, verbose_name='Поле7')),
                ('pole8', models.CharField(max_length=10000, verbose_name='Поле8')),
                ('pole9', models.CharField(max_length=30, verbose_name='Поле9')),
                ('pole10', models.CharField(max_length=500, verbose_name='Поле10')),
            ],
        ),
    ]
