# Generated by Django 3.2.16 on 2023-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_tasksakt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksakt',
            name='pole11',
            field=models.CharField(default='0', max_length=500, verbose_name='Поле11'),
        ),
        migrations.AddField(
            model_name='tasksakt',
            name='pole12',
            field=models.CharField(default='0', max_length=500, verbose_name='Поле12'),
        ),
        migrations.AlterField(
            model_name='tasksakt',
            name='pole6',
            field=models.CharField(max_length=100, verbose_name='Поле6'),
        ),
        migrations.AlterField(
            model_name='tasksakt',
            name='pole7',
            field=models.CharField(max_length=200, verbose_name='Поле7'),
        ),
        migrations.AlterField(
            model_name='tasksakt',
            name='pole8',
            field=models.CharField(max_length=100, verbose_name='Поле8'),
        ),
        migrations.AlterField(
            model_name='tasksakt',
            name='studentId',
            field=models.CharField(max_length=30, verbose_name='Логин ученика'),
        ),
        migrations.AlterField(
            model_name='tasksakt',
            name='teacherId',
            field=models.CharField(max_length=30, verbose_name='Логин учителя'),
        ),
        migrations.AlterField(
            model_name='teachersakt',
            name='idTeacher',
            field=models.CharField(max_length=4000, verbose_name='Логин учителя'),
        ),
        migrations.AlterField(
            model_name='teachersakt',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teachersakt',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Фамилиия'),
        ),
    ]
